### ISSUE TITLE
panic in  `disk_cache::test::test_disk_cache_store_get_range`

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb#592]
### Describe this problem

When I run `codecov` I get the following error:
```
failures:
---- disk_cache::test::test_disk_cache_store_get_range stdout ----
thread 'main' panicked at 'range end out of bounds: 1 <= 0', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.2.1/src/bytes.rs:261:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:142:14
   2: <bytes::bytes::Bytes>::slice::<core::ops::range::Range<usize>>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.2.1/src/bytes.rs:261:9
   3: <object_store::disk_cache::DiskCacheStore as object_store::ObjectStore>::get_range::{closure#0}
             at ./src/disk_cache.rs:459:26
   4: <core::future::from_generator::GenFuture<<object_store::disk_cache::DiskCacheStore as object_store::ObjectStore>::get_range::{closure#0}> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/mod.rs:91:19
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<bytes::bytes::Bytes, object_store::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/future.rs:124:9
   6: object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}
             at ./src/disk_cache.rs:610:56
   7: <core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/mod.rs:91:19
   8: <core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/future.rs:124:9
   9: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:541:57
  10: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/coop.rs:102:5
  11: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/coop.rs:68:5
  12: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:541:25
  13: <tokio::runtime::scheduler::current_thread::Context>::enter::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:350:19
  14: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:540:36
  15: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}, core::option::Option<()>>::{closure#0}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:615:57
  16: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::current_thread::Context>>::set::<<tokio::runtime::scheduler::current_thread::CoreGuard>::enter<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}, core::option::Option<()>>::{closure#0}, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core>, core::option::Option<()>)>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/macros/scoped_tls.rs:61:9
  17: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>::{closure#0}, core::option::Option<()>>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:615:27
  18: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:530:19
  19: <tokio::runtime::scheduler::current_thread::CurrentThread>::block_on::<core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/current_thread.rs:154:24
  20: <tokio::runtime::runtime::Runtime>::block_on::<core::future::from_generator::GenFuture<object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}>>
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/runtime.rs:282:47
  21: object_store::disk_cache::test::test_disk_cache_store_get_range
             at ./src/disk_cache.rs:630:9
  22: object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0}
             at ./src/disk_cache.rs:584:11
  23: <object_store::disk_cache::test::test_disk_cache_store_get_range::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/ops/function.rs:248:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps to reproduce

Refer to https://github.com/CeresDB/ceresdb/actions/runs/4034840337/jobs/6936355253

**Comment by tanruixiang** [comment]
It may have been fixed, and if it reappears, the issue will reopen.
